import Foundation
import UIKit


class MockService{

    public static let shared = MockService()

    func getData() -> [GuideDataObject] {
        return [
            GuideDataObject(image: UIImage(named:"m64"), name: "Super Mario 64", title: "Super Mario 64 Walkthrough! Find all the secret Stars!", text: "Our Super Mario 64 stars guide covers all 120 Power Stars hidden throughout Peach’s Castle. The goal of our guide is to get you the locations and any necessary information for each star in the quickest way possible. Look out for short and to the point descriptions along with images and maps. Super Mario 64 features 15 different worlds, each with a total of seven collectible Power Stars. Six stars are based on the level picked before entering the world but there’s also a star reward for collecting 100 coins without leaving the level. Some of these stars can be found no matter which level you choose and we’ll make that distinction throughout our Super Mario 64 stars walkthrough.",deviceicon: UIImage(named: "n64"),platform: "Nintendo 64", icon: UIImage(named: "super-mario"), autor: "MarioGalaxyParty"),
            
            GuideDataObject(image: UIImage(named:"zelda"), name: "The Legend of Zelda",title: "TLoZ NES Walkthrough, don't miss any secret chest!", text: "Welcome to the Legend of Zelda Walkthrough. The walkthrough below is a complete 100% guide through of the entire game, along with miscellaneous guides for the various collectibles, oddball secrets, and everything else there is to find in the game. Additionally, we have a complete Video Walkthrough of the Legend of Zelda.",deviceicon: UIImage(named: "nespad"),platform: "NES", icon: UIImage(named: "z2"), autor: "ZeldaStars"),
            
            GuideDataObject(image: UIImage(named:"tr"), name: "Tomb Raider",title: "Tomb Raider PS1 Walkthrough. Uncover all its secrets!", text: "This classic video game is where it all began. In November 1996, players around the world got their first glimpse of intrepid British adventurer Lara Croft. Tomb Raider  was created in about 18 months by a six-person team at Core Design in Derby, England. It was hailed by critics and players alike as a ground-breaking action-adventure title and has gone on to sell more than 8 million copies.",deviceicon: UIImage(named: "ps"),platform: "Playstation 1", icon: UIImage(named: "playstation"), autor: "TombRaiders"),
            
            GuideDataObject(image: UIImage(named:"fable"), name: "Fable Anniversary",title: "Fable Walkthrough, discover all the pathaways!", text: "The world of Fable can be overwhelming at times and even when you master the basics there are plenty of secrets to boggle the minds of the most experienced adventurers. With so many options you may not know where to start. There are people to talk to, women to flirt with, chickens to kick, and tats to have inked. We start you off with the basics and then delve into the many options you have in Fable. We have also included a detailed guide to wooing lovely ladies, robbing a town blind, dominating the pub games and completing every side quest in the world of Albion. But thats not all, we give more love with: ",deviceicon: UIImage(named: "xboxpad"),platform: "Xbox", icon: UIImage(named: "fableicon"), autor: "Gamespy"),
            
            GuideDataObject(image: UIImage(named:"fnt"), name: "Fortnite",title: "Fornite New Season is out! Get all the new skins!", text: "Fortnite is celebrating the spooky season with the annual release of Fortnitemares, which itself has brought a tonne of new Halloween-themed content into the game. With all the new content in the game, it can be quite hard to get a grasp on everything this new event has to offer. But KeenGamer has you covered. From how to complete all the new quests, to understanding how to get the new Mythic and Rare items, here is your guide to Fortnitemares 2022. How To Get The Howler Claws: While the many map alterations give the Fortnite island a fresh new look, the biggest change is the inclusion of the new Mythic Howler Claws. The Howler Claws are an item of Mythic rarety that grants players access to three unique abilities once equipped. These abilities are: Wolfscent Ability: Reveals all opponents close to you (Players who are nearby will be warned of your presence via an audio cue), Slash Ability: A deadly melee combo that deals damage upon every swing, Air Slash Ability: Perform a lunge forward followed by a clawed swipe. Unlike most ground loot, players will have to complete a series of steps in order to obtain this new powerful item. The first step is to head to one of the Alteration Altars, which can be found at the Reality Tree as well as various other locations on the map. The below image details all the altar locations.",deviceicon: UIImage(named: "mobile"),platform: "Mobile", icon: UIImage(named: "fortnite"), autor: "Keengamer"),
            
            GuideDataObject(image: UIImage(named:"me"), name: "Mass Effect",title: "Mass Effect walkthrough. The Reapers don't stand a chance!", text: "Mass Effect Legendary Edition takes the fan-favorite Shepard trilogy and packages it into one enhanced remaster that contains over 40 DLC packs. EA removed the multiplayer from Mass Effect 3 for the Legendary Edition but has also made a number of tweaks and fixes to enhance the overall gameplay of all three titles. The first Mass Effect, in particular, has been given an array of quality of life improvements, such as improved Mako controls, better AI behavior, weapon balancing, and more. Mass Effect has long been celebrated as one of the best franchises for its engaging storyline, in-depth characters, and a world that can be shaped by player decisions. For everything you need to know about the Mass Effect: Legendary Edition, we've got it all covered right here.",deviceicon: UIImage(named: "kb"),platform: "PC", icon: UIImage(named: "N7S"), autor: "Thegamer"),
            
            GuideDataObject(image: UIImage(named:"doom93"), name: "Doom 93",title: "Original Doom walkthrough. Unveil your inner demon-hunter!", text: "DOOM (1993) is yet another port of the classic MS-DOS game. For those that are not familiar with the game, it is a first-person shooter. The game puts the player on a Mars base where demons and creatures from Hell appear. The player, controlling a space marine referred to as Doomguy by fans, must navigate through the base and eventually navigate through Hell itself. It is an extremely fast-paced game, especially on the higher difficulties. There are a variety of different weapons and enemies to contend with. It was also one of the first first-person shooters to feature a versus mode, and takes credit for coining the popular phrase 'Deathmatch'.Without further ado, let's get started with the basics on the next page.",deviceicon: UIImage(named: "kb"),platform: "PC", icon: UIImage(named: "doom"), autor: "Trueachievements")
        ]
    }
}
